### PR TITLE
Make re2 an optional peer dependency

### PR DESCRIPTION
**Pull request by KevinNovak**
Address issue #23. This is basically Option 1 in #18.

### CODE REVIEW

**Comment by KevinNovak** [comment]
Looks like some of the scripts, like the "test-coverage" script run by the CI, requires `re2` to be installed. Not sure the best action to take here.

**Comment by niftylettuce** [comment]
Add re2 to devDependencies

**Comment by niftylettuce** [comment]
I'll manually add it and version bump and fix lockfile.

**Comment by niftylettuce** [comment]
See v3.0.0 https://github.com/spamscanner/url-regex-safe/releases/tag/v3.0.0

**Pull request merged**
