### PR TITLE
Typescript typings

### PR DESCRIPTION
**Pull request by stuartlong**
Adds basic Typescript typings for consumption from Typescript projects.

### CODE REVIEW

**Comment by niftylettuce** [comment]
Sorry, I don't support TypeScript.  It's bad for the community and bad for open source JavaScript.

**Comment by niftylettuce** [comment]
Thank you again though @stuartlong - you could possibly add this in @DefinitelyTyped or whatever that thing is

**Comment by trevyn** [comment]
@niftylettuce Could you explain your view? TypeScript is open source.

**Comment by niftylettuce** [comment]
See https://github.com/breejs/bree/pull/16#issuecomment-672756303.  I don't write TS and don't use TS.  It slows me down, and I speak on experience though and some very opinionated views if you see my GH.

**Pull request closed without merging**
